//{{NO_DEPENDENCIES}}
// Microsoft Visual C++에서 생성한 포함 파일입니다.
// HeaderStoneDeckMaker.rc에서 사용되고 있습니다.
//
#define IDC_RESET_BTN                   2
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_HEADERSTONE_DECK_MAKER_DIALOG 102
#define IDR_MAINFRAME                   128
#define IDD_FILTER_DLG                  130
#define IDD_LOADING_DATA_PROGRESS_DLG   132
#define IDD_DECKCODE_DLG                134
#define IDR_MENU                        137
#define IDD_IMPORT_BY_METADECK_DLG      138
#define IDC_CLASS_DRUID_RDO             1006
#define IDC_CLASS_HUNTER_RDO            1007
#define IDC_CLASS_MAGE_RDO              1008
#define IDC_CLASS_PALADIN_RDO           1009
#define IDC_CLASS_PRIEST_RDO            1010
#define IDC_CLASS_ROGUE_RDO             1011
#define IDC_CLASS_WARLOCK_RDO           1012
#define IDC_CLASS_SHAMAN_RDO            1013
#define IDC_CLASS_WARRIOR_RDO           1014
#define IDC_CLASS_FREE_RDO              1015
#define IDC_BUTTON1                     1017
#define IDC_FILTER_BTN                  1017
#define IDC_CARD_PAGE                   1018
#define IDC_DECK_LIST                   1019
#define IDC_CARDTYPE_MINION_CHK         1021
#define IDC_CARDTYPE_SPELL_CHK          1022
#define IDC_CARDTYPE_WEAPON_CHK         1023
#define IDC_CARDTYPE_HERO_CHK           1024
#define IDC_CARDSTAT_COST_FROM_EDT      1025
#define IDC_CARDSET_ORIGINAL_CHK        1026
#define IDC_CARDSET_WITCHWOOD_CHK       1027
#define IDC_CARDSET_BOOM_S_DAY_CHK      1028
#define IDC_CARDSET_RUMBLE_CHK          1029
#define IDC_CARDSET_RISE_OF_SHADOW_CHK  1030
#define IDC_CARDSET_HALL_OF_FAME_CHK    1031
#define IDC_CARDSET_NAXX_CHK            1032
#define IDC_CARDSET_GOBLIN_GNOMES_CHK   1033
#define IDC_CARDSET_BLACKROCK_CHK       1034
#define IDC_CARDSET_TOURNAMENT_CHK      1035
#define IDC_CARDSET_EXPLORERS_CHK       1036
#define IDC_CARDSET_OLDGOD_CHK          1037
#define IDC_CARDSET_KARAZHAN_CHK        1038
#define IDC_CARDSET_GADGETZAN_CHK       1039
#define IDC_CARDSET_UNGORO_CHK          1040
#define IDC_CARDSET_FROZEN_THRONE_CHK   1041
#define IDC_CARDSET_COBOLTS_CHK         1042
#define IDC_CARDRARIRY_FREE_CHK         1043
#define IDC_CARDRARIRY_COMMON_CHK       1044
#define IDC_CARDRARIRY_RARE_CHK         1045
#define IDC_CARDRARIRY_EPIC_CHK         1046
#define IDC_CARDRARIRY_LEGENDARY_CHK    1047
#define IDC_CARDCLASS_DRUID_CHK         1048
#define IDC_CARDCLASS_HUNTER_CHK        1049
#define IDC_CARDCLASS_MAGE_CHK          1050
#define IDC_CARDCLASS_PALADIN_CHK       1051
#define IDC_CARDCLASS_PRIEST_CHK        1052
#define IDC_CARDCLASS_ROGUE_CHK         1053
#define IDC_CARDCLASS_SHAMAN_CHK        1054
#define IDC_CARDCLASS_WARLOCK_CHK       1055
#define IDC_CARDCLASS_WARRIOR_CHK       1056
#define IDC_CARDCLASS_NONE_CHK          1057
#define IDC_CARDRACE_MURLOC_CHK         1058
#define IDC_CARDRACE_DEMON_CHK          1059
#define IDC_CARDRACE_BEAST_CHK          1060
#define IDC_CARDRACE_DRAGON_CHK         1061
#define IDC_CARDRACE_TOTEM_CHK          1062
#define IDC_CARDRACE_PIRATE_CHK         1063
#define IDC_CARDRACE_MECH_CHK           1064
#define IDC_CARDRACE_ELEMENTAL_CHK      1065
#define IDC_CARDSTAT_COST_TO_EDT        1066
#define IDC_CARDSTAT_ATK_FROM_EDT       1067
#define IDC_CARDSTAT_ATK_TO_EDT         1068
#define IDC_CARDSTAT_HLT_FROM_EDT       1069
#define IDC_CARDSTAT_HLT_TO_EDT         1070
#define IDC_CARDSTAT_TEXT_EDT           1071
#define IDC_CARDTYPE_STC                1072
#define IDC_CARDSET_STC                 1073
#define IDC_CARDSET_REGULAR_STC         1074
#define IDC_CARDSET_WILD_STC            1075
#define IDC_CARDRARIRY_STC              1076
#define IDC_CARDCLASS_STC               1077
#define IDC_CARDRACE_STC                1078
#define IDC_CARDSTAT_STC                1079
#define IDC_CARDSTAT_COST_STC2          1081
#define IDC_CARDSTAT_ATK_STC2           1083
#define IDC_CARDSTAT_HLT_STC2           1085
#define IDC_CARDSTAT_TEXT_STC           1086
#define IDC_EXPORT_DECK_CODE_BTN        1088
#define IDC_CARDTYPE_CHK                1089
#define IDC_IMPORT_DECK_CODE_BTN        1089
#define IDC_CARDSET_CHK                 1090
#define IDC_CARDRARITY_CHK              1091
#define IDC_CARDCLASS_CHK               1093
#define IDC_CARDRACE_CHK                1094
#define IDC_CARDCOST_CHK                1095
#define IDC_CARDATTACK_CHK              1096
#define IDC_CARDHEALTH_CHK              1097
#define IDC_CARDTEXT_CHK                1098
#define IDC_PROGRESS_BAR                1099
#define IDC_LOADING_STC                 1100
#define IDC_AMOUNT_STC                  1101
#define IDC_DECKCODE_EDT                1102
#define IDC_IMPORT_SPL                  1104
#define IDC_DECKCLASS_CMB               1105
#define IDC_DECKTYPE_CMB                1106
#define IDC_DECK_AVG_LENGTH_EDT         1108
#define IDC_DECK_AVG_TURN_EDT           1109
#define IDC_DECKCLASS_STC               1110
#define IDC_DECKTYPE_STC                1111
#define IDC_DECK_TOTAL_GAMES_EDT        1112
#define IDC_DECK_WIN_RATE_EDT           1113
#define IDC_DECKINFO_STC                1114
#define IDC_DECK_AVG_LENGTH_STC         1115
#define IDC_DECK_AVG_LENGTH_STC2        1116
#define IDC_DECK_AVG_TURN_STC           1117
#define IDC_DECK_TOTAL_GAMES_STC        1118
#define IDC_DECK_WIN_RATE_STC           1119
#define IDC_DECK_WIN_RATE_STC2          1120
#define ID_IMPORT_IMPORTBYDECKCODE      32771
#define ID_IMPORT_IMPORTMETADECK        32772

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        140
#define _APS_NEXT_COMMAND_VALUE         32773
#define _APS_NEXT_CONTROL_VALUE         1121
#define _APS_NEXT_SYMED_VALUE           104
#endif
#endif
